### ISSUE TITLE
Establishing MQTT connection to AWS IoT

### ISSUE THREAD

**Issue by Gomathi-N** [njh/ruby-mqtt#111]
I am in need of establishing MQTT connection from my rails API. I have used the gem ruby-mqtt. Refer this link for the gem https://github.com/njh/ruby-mqtt. Everything works fine after establishing connection from my rails API using the certificates from AWS IoT.

How can I establish a secure connection without using certificates? Is it possible to publish messages by using AWS secret access key ?

**Comment by njh** [comment]
This seems to be a question about AWS IoT, rather than ruby-mqtt.

I have never using AWS IoT myself but this page seems to imply that the only supported authentication mechanism is via client certificates:
https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

Is there a reason for not wanting to use client certificates?

**Comment by njh** [comment]
No response, so closing issue.
