### ISSUE TITLE
How to handle sigterm?

### ISSUE THREAD

**Issue by 9mm** [njh/ruby-mqtt#145]
I'm using this in a sidekiq job (not the best place for it I realize, in the name of time I'm not daemonizing)

The only thing is, is there a way I can check something inside the local loop in the gem?

This obviously only works when there's a message, but otherwise it will get SIGKILL

```
      client.get do |topic, message|
        break if $sidekiq_shutdown_pending
        puts topic, message
      end
```

**Comment by softwaregravy** [comment]
You can rescue interrupts in Ruby. Here's a [blogpost](https://airbrake.io/blog/ruby-exception-handling/interrupt) (not mine) talking a bit about it. So you'd have to wrap the code in a `begin` block and then `rescue` the interrupt. 

If instead of what you have there, you were to do:
```ruby
MQTT::Client.connect(...) do |c|
   ...
end
```
Then your [code would be wrapped in an ensure block](https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt/client.rb#L286) which should exit cleanly.

**Comment by 9mm** [comment]
awesome thank you

**Comment by dentarg** [comment]
You can also define your own signal handlers: https://ruby-doc.org/3.3.3/Signal.html, https://github.com/ruby/ruby/blob/master/doc/signals.rdoc (`Signal.trap`)

**Comment by dentarg** [comment]
I think this issue should be closed. It is more a general Ruby question, and not something to be addressed in this gem.
