### ISSUE TITLE
Failed to read byte from socket(MQTT::ProtocolException)

### ISSUE THREAD

**Issue by arjayx** [njh/ruby-mqtt#63]
hi @njh 
sorry to comment in other issues.

##### the code of mqtt client :

``` ruby
require "mqtt"

c = MQTT::Client.connect(
  host: '192.168.1.5', 
  port: 1883,
  username: 'guest',
  password: 'guest')

loop do
  m = "Message mqtt sended @ #{Time.now.to_i} " 
  c.publish("builds", m)
  puts "=> Published #{m}"
  sleep 0.2
end

```

##### the error is :
``` ruby
railpc@railpc-VirtualBox:/media/sf_ProjectRubyLinux/Ruby/Semillero$ ruby producer_mqtt.rb 
=> Published Message mqtt sended @ 1430402156 
/home/railpc/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mqtt-0.3.1/lib/mqtt/packet.rb:283:in `read_byte': Failed to read byte from socket (MQTT::ProtocolException)
	from /home/railpc/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mqtt-0.3.1/lib/mqtt/packet.rb:31:in `read'
	from /home/railpc/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:454:in `receive_packet'
	from /home/railpc/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mqtt-0.3.1/lib/mqtt/client.rb:283:in `block in connect'
```

##### the broker have is configuration in rabbitmq.config :

``` ruby
[
 {rabbit, [
        %%=====================================
        %%----Configuration of AMQP protocol----
        %% =====================================

        {tcp_listeners, [{"192.168.1.5", 5672}]},
        {default_user, <<"guest">>},
        {default_pass, <<"guest">>},
        {default_permissions, [<<".*">>, <<".*">>, <<".*">>]},
        {default_vhost, <<"/">>},
        {loopback_users, []}
 ]},
        %%-----------------------------------------------------

        %%======================================
        %%----Configuration Of MQTT protocol----
        %%======================================
 {rabbitmq_mqtt,[
        {vhost,<<"semillero">>},
        {default_user, << "guest">>},
        {default_pass, <<"guest">>},
        {exchange, <<"amp.topic">>},
        {tcp_listeners,[{"192.168.1.5", 1883}]},
        {allow_anonymous, true}

 ]}
        %%-----------------------------------------------------
].

```

Thanks @njh .

**Comment by arjayx** [comment]
Hi @njh 
sorry
I 'm new in github.
Did you can to see some bad in the code?
Thanks :+1

**Comment by njh** [comment]
Hello,

Unfortunately 'Failed to read byte from socket (MQTT::ProtocolException)' is a bit of a cryptic error, that actually means the server closed the network socket - I have tried to improve this error message but not found a way of doing it.

Other than when first establishing the connection, MQTT does not have a mechanism for telling the client when it has done something wrong - it will just disconnect the client. In order to know what went wrong, you have to look at the servers logs.


I have modified your code slightly to work on my machine, and it is working fine with Mosquitto:

```ruby
require "mqtt"

c = MQTT::Client.connect(
  host: '127.0.0.1',
  port: 1883
)

loop do
  m = "Message mqtt sent @ #{Time.now.to_i} "
  c.publish("builds", m)
  puts "=> Published #{m}"
  sleep 0.2
end
```

Things to try to solve you problem:
* Check the Rabbit MQ server logs - does it give a reason why it is disconnecting the client? Perhaps the client doesn't have permission to post to that topic?
* Can you send messages using a command line tool, instead of in ruby? Mosquitto provides the mosquitto_pub and mosquitto_sub shell commands.
* Have you tried using a different server, such as Mosquitto?


I hope this helps,

nick.

**Comment by arjayx** [comment]
hi nick.
thanks.
I saw Rabbit MQ file server logs and found the problem. I found that topic to default is "amq.topic" and my file rabbitmq.config had "amp.config"
